### ISSUE TITLE
Possible conflict with the Stripe add-on

### ISSUE THREAD

**Issue by bennemann** [GravityKit/gravity-forms-zero-spam#22]
Report from a user:
> With the recent update to Gravity Forms Stripe add-on 5.1.0, we ran into an issue. 
> 
> Once enabling the Alternate Payment Methods (for Apple/Google Pay, etc). Entries were getting flagged as spam, yet they were getting charged, but the entry process was not completed to provide updated data for the entry, such as the payment ID, process Mailchimp, and Zapier feeds, or send the notification emails to the customer and us.
> 
> When disabling your plugin, everything works fine (except now we are getting spam submissions on our non-payment forms).
> 
> I've been working with the GF support team on issues around Stripe 5.0 and 5.1, and when I reported this information to them, they suggested that I submit this information to you to investigate a potential conflict between the Stripe 5.1.0 add-on and Gravity Forms Zero Spam.

**Comment by zackkatz** [comment]
FreeScout #71168. <br>https://support.gravitykit.com/conversation/71168?folder_id=4

**Comment by malayladu** [comment]
@bennemann I attempted to replicate the problem using **Gravity Forms Stripe add-on versions 5.0.0, 5.1.0, and 5.2.1**. In all these versions, the entry was incorrectly tagged as spam by **Gravity Forms Zero Spam 1.4**, regardless of the `Enable additional payment methods` setting.

Have you managed to reproduce this issue in the same scenario as the customer mentioned? If you have, could you please create a video recording and share it? This would be greatly helpful for me to gain a better understanding of the issue and attempt to replicate it in my local environment.

**Comment by zackkatz** [comment]
@malayladu Please fix the issue based on your testing. We can't assume that the customer's report is correctly identifying the problem.

**Comment by malayladu** [comment]
@zack My apologies. 

I had a dev version and that's the reason it was not working in any case. It didn't run build process to build the plugin and that's why few minified JS & CSS were missing and it was causing the issue.

I tested with GravityFormsStripe 5.2.1 released (actual build) and it's working. 

So, I think we need more details from the customer to understand the scenario. 

@bennemann It would be great if we have more details about this issue or the URL where this form is embedded.

**Comment by malayladu** [comment]
We incorporate the hidden field `gf_zero_spam_key` through JavaScript during form submission. Consequently, if any JavaScript error occurs prior to this code, it can prevent the addition of the hidden field and potentially lead to spam entries.

**Comment by bennemann** [comment]
> bennemann, if you could provide additional details about the issue or the URL where the form is embedded, it would be greatly appreciated.

@malayladu Unfortunately, that ticket is from many months ago and we don't have access to the customer's website or any additional information besides that user report.

At the time, @zackkatz [mentioned](https://gravitykit.slack.com/archives/CDSTQ9QQ0/p1676648716454089?thread_ts=1676630934.050869&cid=CDSTQ9QQ0) that Zero Spam seemed to have a conflict with GF 2.7. 

Additionally, Gravity Forms had released [improved honeypot functionality](https://docs.gravityforms.com/spam-honeypot-enhancements/), so we were suggesting using that when Zero Spam wasn't working well for the user.

**Comment by malayladu** [comment]
@bennemann Ok. Got it.

> Have you managed to reproduce this issue in the same scenario as the customer mentioned?

??

By any chance can we get the admin access from the customer to debug this issue on their website?

**Comment by malayladu** [comment]
**Update**

As per discussion with @bennemann on slack, he will contact the customer and try to get the admin access from the customer. Once we get the admin access, I will resume the work on this issue.

https://gravitykit.slack.com/archives/C727B06MB/p1698399217732919

**Comment by malayladu** [comment]
**Update**

It seems there is an error on user’s [registration](https://spacerocktrailrace.com/register/#form) page and I suspect (I mentioned [here](https://github.com/GravityKit/gravity-forms-zero-spam/issues/22#issuecomment-1781480514)) that’s the reason it’s creating an issue with the Zero Spam plugin.

![Screenshot 2023-10-31 at 9 22 47 PM](https://github.com/GravityKit/gravity-forms-zero-spam/assets/708174/c3ec7392-d799-458f-b053-8fe71537e88a)

![Screenshot 2023-10-31 at 9 22 37 PM](https://github.com/GravityKit/gravity-forms-zero-spam/assets/708174/42dcf964-ef0a-4746-9705-5e7a53e20044)

**Comment by zackkatz** [comment]
Okay, how can we make sure that JS errors don't affect Zero Spam?

**Comment by malayladu** [comment]
@zack We are adding `gf_zero_spam_key` using Javascript on clicking of Submit button. We may need to change this approach and use available Gravity Forms action / filter to add that key.

**Comment by zackkatz** [comment]
The way the functionality works is by using JavaScript to insert the key on-submit.

Does it work when using Gravity Forms JavaScript hooks? 
https://docs.gravityforms.com/category/developers/hooks/javascript/
