### ISSUE TITLE
Forms blocked due to use of deprecated "is_html5_enabled"

### ISSUE THREAD

**Issue by Vinobe93** [GravityKit/gravity-forms-zero-spam#36]
In the class "GF_Zero_Spam" in method "add_key_value" the function `RGFormsModel::is_html5_enabled()` is used.
Gforms throws an warning on this that the function is deprecated with no fallback.
![image](https://github.com/user-attachments/assets/4e133c54-319f-42c6-94f6-cf1c2a653e21)

I'm refering to this line:
![image](https://github.com/user-attachments/assets/1eae12ea-0d62-4f70-926d-66b7205837bb)

If I change the function call to an hardcoded "true" (which is also the fallback for the deprecated function in gravityforms) the form is displayed again as it should.

Expected result: Not showing a php warning and showing the form

Edit: the issue only shows when `define( 'WP_DEBUG_DISPLAY', true );` is set obviously, which is the case on our development environment. But it is a deprecated function nonetheless and should be removed.

**Comment by mrcasual** [comment]
@Vinobe93, thank you for reporting the issue. It has been fixed in [version 1.4.5](https://github.com/GravityKit/gravity-forms-zero-spam/releases/tag/v1.4.5).
